name: Make
on:
  create:
    tags:
      - '*'

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run
        run: ./gen.sh
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: res.tar.xz
